const dummyData = [
  {
    id: 1,
    status: "Active",
    firstName: "John",
    middleName: "Robert",
    lastName: "Doe",
    locationCity: "New York",
    address: "123 Main St",
    dateBirth: "1990-05-15",
    telephone: "555-123-4567",
    positionTitle: "Software Engineer",
    hireDate: "2021-02-10",
    email: "john.doe@example.com",
    salary: 90000,
    timeInPosition: "2 years",
  },
  {
    id: 2,
    status: "Idle",
    firstName: "Jane",
    middleName: "Elizabeth",
    lastName: "Smith",
    locationCity: "Los Angeles",
    address: "456 Oak Ave",
    dateBirth: "1988-09-20",
    telephone: "555-987-6543",
    positionTitle: "Marketing Manager",
    hireDate: "2019-06-05",
    email: "jane.smith@example.com",
    salary: 110000,
    timeInPosition: "4 years",
  },
  {
    id: 3,
    status: "Active",
    firstName: "Michael",
    middleName: "James",
    lastName: "Johnson",
    locationCity: "Chicago",
    address: "789 Elm Rd",
    dateBirth: "1992-03-12",
    telephone: "555-456-7890",
    positionTitle: "Sales Representative",
    hireDate: "2022-01-20",
    email: "michael.johnson@example.com",
    salary: 75000,
    timeInPosition: "1 year",
  },
  {
    id: 4,
    status: "Active",
    firstName: "Emily",
    middleName: "Grace",
    lastName: "Williams",
    locationCity: "San Francisco",
    address: "567 Pine St",
    dateBirth: "1991-07-28",
    telephone: "555-765-4321",
    positionTitle: "Graphic Designer",
    hireDate: "2020-09-15",
    email: "emily.williams@example.com",
    salary: 80000,
    timeInPosition: "2 years",
  },
  {
    id: 5,
    status: "Idle",
    firstName: "Daniel",
    middleName: "Joseph",
    lastName: "Brown",
    locationCity: "Seattle",
    address: "234 Cedar Ave",
    dateBirth: "1989-12-03",
    telephone: "555-234-5678",
    positionTitle: "Project Manager",
    hireDate: "2018-05-01",
    email: "daniel.brown@example.com",
    salary: 120000,
    timeInPosition: "5 years",
  },
];

export default dummyData;
